name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Daily build at midnight UTC
    - cron: '0 0 * * *'

jobs:
  docker:
    name: ROS 2 Docker build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: docker build
        run: docker build . --file Dockerfile.ros-lyrical

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        include:
          - python-version: '3.10'
            os: ubuntu-latest
          - python-version: '3.14'
            os: ubuntu-latest
          - python-version: '3.14'
            os: macos-latest
          - python-version: '3.14'
            os: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install and configure package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          evo_config show --brief --no_color
          
      - name: mypy
        # TODO: check why apsw (via rosbags) has a broken .pyi on 3.10
        if: matrix.python-version != '3.10'
        run: |
          pip install mypy types-PyYAML
          mypy .

      - name: black
        run: |
          pip install black
          black --check .

      - name: pytest
        run: |
          pip install pytest
          pytest -sv

  test-rerun-integration:
    name: Test Rerun integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
 
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install and configure package and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          evo_config show --brief --no_color

      - name: Install Rerun
        run: |
          pip install rerun-sdk
          rerun analytics disable

      - name: Start Rerun gRPC server
        id: rerun-grpc-server
        background: true
        run: rerun --serve-grpc

      - name: Disable rerun_spawn setting
        run: evo_config set rerun_spawn false

      - name: Rerun integration smoke tests
        # TODO: make this a proper test script.
        run: |
          cd test/data
          evo_traj tum fr2_desk_groundtruth.txt fr2_desk_ORB.txt -v --rerun
          evo_ape tum fr2_desk_groundtruth.txt fr2_desk_ORB.txt -v --rerun
          evo_rpe tum fr2_desk_groundtruth.txt fr2_desk_ORB.txt -v --rerun --save_results /tmp/result
          evo_res /tmp/result -v --rerun
      
      - name: Stop Rerun gRPC server
        cancel: rerun-grpc-server

  build:
    name: Build Package
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          
      - name: Build sdist and wheel
        run: |
          pip install hatch
          hatch build
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/